route:
  receiver: telegram
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 2h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "TELEGRAM_BOT_TOKEN"
        chat_id: CHAT_ID
        parse_mode: ""
