global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: windows
    static_configs:
      - targets: ["host.docker.internal:9182"]

  - job_name: node
    static_configs:
      # Если node_exporter с network_mode: host, на Windows он не доступен снаружи.
      # Для Linux-сервера можно указать "localhost:9100".
      - targets: ["localhost:9100", "node_exporter:9100"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres_exporter:9187"]
